name: CI

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libssl-dev build-essential
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Build Binary
        run: go build -o dummy-server.bin ./cmd
      - name: Simple Test
        run: |
          ./dummy-server.bin &
          sleep 3
          curl -v https://localhost:8443
          kill $!
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: binary
          path: ./dummy-server.bin

